# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

menu:
- {name: 'Countries', path: 'menu', url: 'countries.html'}
- {name: 'Archive', path: 'menu', url: 'archive.html'}
- {name: 'Rail Map', path: 'menu', url: 'railmap.html'}
- {name: 'The List', path: 'menu', url: 'thelist.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/andrewsio'}
- {icon: 'twitter', link: 'https://twitter.com/14zz4'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/laurence-andrews/'}
- {icon: 'instagram', link: 'https://www.instagram.com/14zz4/'}
- {icon: 'envelope', link: 'mailto:laurence@andrews.io'}
- {icon: 'rss-square', link: '/feed.xml'}

# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Other Posts:'

post_date_prefix: 'Written on'
